services:
  - type: web
    runtime: python
    name: texas-poker
    plan: free
    autoDeployTrigger: commit
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
